//
//  ViewController.swift
//  Odev6
//
//  Created by İsmail Kocaoglu on 21.01.2024.
//

import UIKit

class ViewController: UIViewController {

    
    @IBOutlet weak var basliklarCollectionView: UICollectionView!
    
    var basliklarListesi = [Basliklar]()
    
    override func viewDidLoad() {
        
        basliklarCollectionView.delegate = self
        basliklarCollectionView.dataSource = self
        
        let f1 = Basliklar(id: 1, resim: "100yil", description: "Ülkemizi işgalden bağımsızlığa, esaretten özgürlüğe ve saltanattan ulusal egemenliğe taşıyan Cumhuriyetimizin ve Ulu Önder Mustafa Kemal Atatürk’ümüzün vizyonundan esinlenerek İstanbul’u geleceğe taşıyoruz.Kurucumuz Gazi Mustafa Kemal Atatürk’ün fotoğrafıyla Cumhuriyetimizin 100. yılına özel İstanbulkartlarımızı sizlerle buluşturmaktan gurur duyuyoruz. Sınırlı sayıdaki isme özel İstanbulkart başvuruları yıl sonuna kadar bireysel.istanbulkart.istanbul adresinde… Çok yaşa Cumhuriyet Kampanya Geçerlilik Tarihi: 31.10.2023-30.12.2023",kullanim: "Herhangi bir koşul bulunmamaktadır.")
        let f2 = Basliklar(id: 2, resim: "otomatik", description: "Yeterli bakiye kalmadığında belirlediği tutarın İstanbulkart’ına yüklenmesi için İstanbulkart Mobil’den otomatik yükleme talimatı veren öğrenci İstanbulkartlılara özel her talimatın %10’u hediye!Kampanya Geçerlilik Tarihi: 31.08.2023-30.09.20",kullanim: "İstanbulkart Mobil’den İşlemler menüsünden, dijital veya fiziksel öğrenci İstanbulkart’ına Otomatik Yükleme Talimatı veren öğrenci kartlar faydalanabilecektir.Talimat veren kullanıcılar gerçekleşen her talimat yüklemesinin %10’unu nakit iade alabilecektir.Bir kullanıcı kampanyaya birden fazla kez katılabilir.Kampanya süresince bir kullanıcının alacağı maksimum ödül tutarı 60 TL’dir. En fazla 3 kez ödüllenebilir.Kampanyaya katılmak için öğrenci İstanbulkart’ın indirimli tarifesinin aktif olması gerekmektedir.Ödül TL, ödeme yapılan dijital veya fiziksel İstanbulkart’a aynı gün talimat olarak yüklenecektir.Fiziksel kartlarda talimat olarak yüklenen ödül TL, İstanbulkart Mobil üzerinden NFC yoluyla, herhangi bir yükleme noktasına, otobüs duraklarında yer alan talimat yükleme noktalarına, otobüslerdeki geçiş cihazlarına İstanbulkart dokundurularak tanımlanabilir.Dijital İstanbulkartlar için herhangi bir tanımlama yapılmasına gerek yoktur doğrudan TL olarak yüklenecektir.Kazanılan ödülün nakit karşılığı talep edilemez.Kampanyadan faydalanabilmek için kampanyaya katılmadan önce İstanbulkart’ın kişiselleştirilmiş olması, açık rıza tercihlerinin açık olması ve en az bir ticari elektronik ileti izninin verilmiş olması gereklidir.Açık rıza ve ticari elektronik ileti izinleri İstanbulkart Mobil’den ya da https://bireysel.istanbulkart.istanbul adresindeki profil sayfasından düzenlenebilir. Kişiselleştirme işlemini yapmak, açık rıza ve ticari elektronik ileti izinlerini en kolay şekilde düzenlemek için bit.ly/istanbulkart_mobil adresinden İstanbulkart Mobil’i indirebilirsiniz. Ödüllendirme bilgisi İstanbulkart Mobil kullanıcılarına push bildirimi ya da SMS olarak yapılacaktır.Sistemsel gecikmelerden kaynaklı ödül TL yüklemelerinde oluşabilecek aksaklıklarda BELBİM AŞ müşteri memnuniyeti kapsamında TL ödül yüklemesini en kısa sürede gerçekleştirecektir.BELBİM AŞ kampanyayı durdurma ve değişiklik yapma hakkını saklı tutar.")
        let f3 = Basliklar(id: 3, resim: "ogrenci", description: "Öğrenci İstanbulkartlılara özel QR kodla 10 Geç 9 Öde!Kampanya Geçerlilik Tarihi: 31.08.2023-30.09.2023",kullanim: "Kampanyadan İstanbulkart Mobil’e ilk kez giriş yapan öğrenciler faydalanabilecektir.İstanbulkart Mobil’den QR ile yapılan 10 geçiş sonrası son geçiş kullanıcının dijital İstanbulkart’ına iade edilecektir.Bir kullanıcı kampanyaya en fazla 3 kere katılabilir.Ödül tutarı ortalama geçiş tutarı belirlenmiştir.Kullanıcının 10. geçişi 7,32 TL üzerinde olmadığı sürece son geçiş tutarı ödül TL olarak yüklenir. Geçiş tutarının 7,32 üzerinde olduğu durumda maksimum 7,32 TL iade edilecektir.QR kodla geçiş özelliği Marmaray, otobüs, metrobüs, metro ve Şehir Hatları olmak üzere tüm toplu ulaşım geçerli ödeme noktalarında kullanılabilmektedir.Kampanyaya katılmak için öğrenci İstanbulkart’ın indirimli tarifesinin aktif olması gerekmektedir.Ödül TL, ödeme yapılan dijital İstanbulkart’a aynı gün yüklenecektir.Kazanılan ödülün nakit karşılığı talep edilemez.Kampanyadan faydalanabilmek için kampanyaya katılmadan önce açık rıza tercihlerinin açık olması ve en az bir ticari elektronik ileti izninin verilmiş olması gereklidir.Açık rıza ve ticari elektronik ileti izinleri İstanbulkart Mobil’den ya da https://bireysel.istanbulkart.istanbul adresindeki profil sayfasından düzenlenebilir.Kişiselleştirme işlemini yapmak, açık rıza ve ticari elektronik ileti izinlerini en kolay şekilde düzenlemek için bit.ly/istanbulkart_mobil adresinden İstanbulkart Mobil’i indirebilirsiniz.Ödüllendirme bilgisi İstanbulkart Mobil kullanıcılarına push bildirimi ya da SMS olarak yapılacaktır.Sistemsel gecikmelerden kaynaklı ödül TL yüklemelerinde oluşabilecek aksaklıklarda BELBİM AŞ müşteri memnuniyeti kapsamında TL ödül yüklemesini en kısa sürede gerçekleştirecektir.BELBİM AŞ kampanyayı durdurma ve değişiklik yapma hakkını saklı tutar.")
        let f4 = Basliklar(id: 4, resim: "legoland", description: "Madame Tussauds markasının sanat, spor ve siyaset dünyasından tarihi ve kültürel kahramanlarının İstanbul'daki evine konuk olmak ve/veya İstanbul'un eğlenceli LEGO gezilerine, LEGO parçalarının yapım sırrının anlatıldığı LEGO fabrika turuna, efektlerle zenginleştirilmiş 4 boyutlu sinemaya şahit olmak için ödeme yöntemi olarak İstanbulkart'ı seçenlere özel İki Bilet Alana Bir Bilet Hediye! Tekli bilet alımlarında ise %30 indirim fırsatı!Kampanya Geçerlilik Tarihi: 01.01.2024-31.12.2024",kullanim: "Herhangi bir koşul mevcut değildir.")
        let f5 = Basliklar(id: 5, resim: "parket", description: "Aracını İSPARK’a park et, ödemeni İstanbulkart ile yap, 2 geçişe kadar ödemen nakit iade! Aracını kampanya dahilindeki Yenikapı İSPARK’a park edip ödemeni İstanbulkart’ın ile yap, aynı gün kullanacağın PD1 hatlı otobüste 2 geçişe kadar nakit iade kazan! Kampanya Geçerlilik Tarihi: 11.08.2023-31.03.2024",kullanim: "Masterpass’e kayıtlı Mastercard logolu Garanti BBVA kartları ile İstanbulkart Mobil’deki İşlemler menüsünden, dijital veya fiziksel İstanbulkart’ına 100 TL ve üzeri otomatik yükleme talimatı veren kullanıcıların gerçekleşen 1. talimatında 25 TL, 2. talimatında ise 25 TL İstanbulkartlarına hediye edilecektir.• Kasım ayında kampanyaya katılıp toplamda 25 TL ödül kazanan kullanıcılar Aralık ayında aynı kampanyadan faydalanamayacaktır. Ancak Kasım ayında ilk talimatında ödül kazanıp ikinci talimatını gerçekleştirmeyen kullanıcılar Aralık ayında verecekleri ikinci talimatlarında kampanyadan faydalanabilecektir. • Kampanyaya Mastercard logolu Bonus, Paracard Bonus, Miles&Smiles Garanti BBVA, Shop&Fly bireysel kartları dahildir.• Kampanyaya ek kart, sanal kart ve personel dahildir.• FastPay ile yapılan işlemler kampanyaya dahil değildir. • Bir kullanıcı kampanyaya birden fazla kez katılabilir.• Kampanya süresince bir kullanıcının alacağı maksimum ödül tutarı 50 TL’dir.• Ödül TL, ödeme yapılan dijital veya fiziksel İstanbulkart’a aynı gün yüklenecektir.• Fiziksel kartlarda talimat olarak yüklenen ödül TL, İstanbulkart Mobil üzerinden NFC yoluyla, herhangi bir yükleme noktasına, otobüs duraklarında yer alan talimat yükleme noktalarına, otobüslerdeki geçiş cihazlarına İstanbulkart dokundurularak tanımlanabilir.• Dijital İstanbulkartlar için herhangi bir tanımlama yapılmasına gerek yoktur doğrudan TL olarak yüklenecektir.• Kazanılan ödül TL’nin nakit karşılığı talep edilemez.• BELBİM AŞ’nin sunduğu kampanyalardan faydalanabilmek için kampanyaya katılmadan önce İstanbulkart’ın kişiselleştirilmiş olması, açık rıza tercihlerinin açık olması ve en az bir ticari elektronik ileti izninin verilmiş olması gereklidir.• Açık rıza ve ticari elektronik ileti izinleri İstanbulkart Mobil’den ya da https://bireysel.istanbulkart.istanbul adresindeki profil sayfasından düzenlenebilir.• Kişiselleştirme işlemini yapmak, açık rıza ve ticari elektronik ileti izinlerini en kolay şekilde düzenlemek için bit.ly/istanbulkart_mobil adresinden İstanbulkart Mobil’i indirebilirsiniz.• Ödüllendirme bilgisi İstanbulkart Mobil kullanıcılarına push bildirimi ya da SMS olarak yapılacaktır.• Sistemsel gecikmelerden kaynaklı ödül TL yüklemelerinde oluşabilecek aksaklıklarda BELBİM AŞ müşteri memnuniyeti kapsamında TL ödül yüklemesini en kısa sürede gerçekleştirecektir.• Belbim AŞ ve Garanti BBVA kampanyayı durdurma ve değişiklik yapma hakkını saklı tutar")
        
        
        let f6 = Basliklar(id: 6, resim: "beltur", description: "Beltur restoran, burger, kafe ve büfelerinde yapacağın İstanbulkart ödemelerinin %20'si ödeme yaptığın İstanbulkart'ına iade!Kampanya Geçerlilik Tarihi: 31.07.2023-31.08.2023",kullanim: "Masterpass’e kayıtlı Mastercard logolu Garanti BBVA kartları ile İstanbulkart Mobil’deki İşlemler menüsünden, dijital veya fiziksel İstanbulkart’ına 100 TL ve üzeri otomatik yükleme talimatı veren kullanıcıların gerçekleşen 1. talimatında 25 TL, 2. talimatında ise 25 TL İstanbulkartlarına hediye edilecektir.• Kasım ayında kampanyaya katılıp toplamda 25 TL ödül kazanan kullanıcılar Aralık ayında aynı kampanyadan faydalanamayacaktır. Ancak Kasım ayında ilk talimatında ödül kazanıp ikinci talimatını gerçekleştirmeyen kullanıcılar Aralık ayında verecekleri ikinci talimatlarında kampanyadan faydalanabilecektir. • Kampanyaya Mastercard logolu Bonus, Paracard Bonus, Miles&Smiles Garanti BBVA, Shop&Fly bireysel kartları dahildir.• Kampanyaya ek kart, sanal kart ve personel dahildir.• FastPay ile yapılan işlemler kampanyaya dahil değildir. • Bir kullanıcı kampanyaya birden fazla kez katılabilir.• Kampanya süresince bir kullanıcının alacağı maksimum ödül tutarı 50 TL’dir.• Ödül TL, ödeme yapılan dijital veya fiziksel İstanbulkart’a aynı gün yüklenecektir.• Fiziksel kartlarda talimat olarak yüklenen ödül TL, İstanbulkart Mobil üzerinden NFC yoluyla, herhangi bir yükleme noktasına, otobüs duraklarında yer alan talimat yükleme noktalarına, otobüslerdeki geçiş cihazlarına İstanbulkart dokundurularak tanımlanabilir.• Dijital İstanbulkartlar için herhangi bir tanımlama yapılmasına gerek yoktur doğrudan TL olarak yüklenecektir.• Kazanılan ödül TL’nin nakit karşılığı talep edilemez.• BELBİM AŞ’nin sunduğu kampanyalardan faydalanabilmek için kampanyaya katılmadan önce İstanbulkart’ın kişiselleştirilmiş olması, açık rıza tercihlerinin açık olması ve en az bir ticari elektronik ileti izninin verilmiş olması gereklidir.• Açık rıza ve ticari elektronik ileti izinleri İstanbulkart Mobil’den ya da https://bireysel.istanbulkart.istanbul adresindeki profil sayfasından düzenlenebilir.• Kişiselleştirme işlemini yapmak, açık rıza ve ticari elektronik ileti izinlerini en kolay şekilde düzenlemek için bit.ly/istanbulkart_mobil adresinden İstanbulkart Mobil’i indirebilirsiniz.• Ödüllendirme bilgisi İstanbulkart Mobil kullanıcılarına push bildirimi ya da SMS olarak yapılacaktır.• Sistemsel gecikmelerden kaynaklı ödül TL yüklemelerinde oluşabilecek aksaklıklarda BELBİM AŞ müşteri memnuniyeti kapsamında TL ödül yüklemesini en kısa sürede gerçekleştirecektir.• Belbim AŞ ve Garanti BBVA kampanyayı durdurma ve değişiklik yapma hakkını saklı tutar")
        
        let f7 = Basliklar(id: 7, resim: "kampanya", description: "İstanbulkart Mobil’den dijital veya fiziksel İstanbulkart’ına Masterpass’e kayıtlı Mastercard logolu Garanti BBVA kartlarınla otomatik yükleme talimatı ver; ilk 100 TL yüklemene 25 TL, ikinci 100 TL yüklemene 25 TL hediye kazan! Kampanya Geçerlilik Tarihi: 13.11.2023-31.12.2023",kullanim: "Masterpass’e kayıtlı Mastercard logolu Garanti BBVA kartları ile İstanbulkart Mobil’deki İşlemler menüsünden, dijital veya fiziksel İstanbulkart’ına 100 TL ve üzeri otomatik yükleme talimatı veren kullanıcıların gerçekleşen 1. talimatında 25 TL, 2. talimatında ise 25 TL İstanbulkartlarına hediye edilecektir.• Kasım ayında kampanyaya katılıp toplamda 25 TL ödül kazanan kullanıcılar Aralık ayında aynı kampanyadan faydalanamayacaktır. Ancak Kasım ayında ilk talimatında ödül kazanıp ikinci talimatını gerçekleştirmeyen kullanıcılar Aralık ayında verecekleri ikinci talimatlarında kampanyadan faydalanabilecektir. • Kampanyaya Mastercard logolu Bonus, Paracard Bonus, Miles&Smiles Garanti BBVA, Shop&Fly bireysel kartları dahildir.• Kampanyaya ek kart, sanal kart ve personel dahildir.• FastPay ile yapılan işlemler kampanyaya dahil değildir. • Bir kullanıcı kampanyaya birden fazla kez katılabilir.• Kampanya süresince bir kullanıcının alacağı maksimum ödül tutarı 50 TL’dir.• Ödül TL, ödeme yapılan dijital veya fiziksel İstanbulkart’a aynı gün yüklenecektir.• Fiziksel kartlarda talimat olarak yüklenen ödül TL, İstanbulkart Mobil üzerinden NFC yoluyla, herhangi bir yükleme noktasına, otobüs duraklarında yer alan talimat yükleme noktalarına, otobüslerdeki geçiş cihazlarına İstanbulkart dokundurularak tanımlanabilir.• Dijital İstanbulkartlar için herhangi bir tanımlama yapılmasına gerek yoktur doğrudan TL olarak yüklenecektir.• Kazanılan ödül TL’nin nakit karşılığı talep edilemez.• BELBİM AŞ’nin sunduğu kampanyalardan faydalanabilmek için kampanyaya katılmadan önce İstanbulkart’ın kişiselleştirilmiş olması, açık rıza tercihlerinin açık olması ve en az bir ticari elektronik ileti izninin verilmiş olması gereklidir.• Açık rıza ve ticari elektronik ileti izinleri İstanbulkart Mobil’den ya da https://bireysel.istanbulkart.istanbul adresindeki profil sayfasından düzenlenebilir.• Kişiselleştirme işlemini yapmak, açık rıza ve ticari elektronik ileti izinlerini en kolay şekilde düzenlemek için bit.ly/istanbulkart_mobil adresinden İstanbulkart Mobil’i indirebilirsiniz.• Ödüllendirme bilgisi İstanbulkart Mobil kullanıcılarına push bildirimi ya da SMS olarak yapılacaktır.• Sistemsel gecikmelerden kaynaklı ödül TL yüklemelerinde oluşabilecek aksaklıklarda BELBİM AŞ müşteri memnuniyeti kapsamında TL ödül yüklemesini en kısa sürede gerçekleştirecektir.• Belbim AŞ ve Garanti BBVA kampanyayı durdurma ve değişiklik yapma hakkını saklı tutar")
        
        let f8 = Basliklar(id: 8, resim: "alısveris", description: "İstanbulkart ile hafta içi 500 TL ve üstü alışverişine, hafta sonu yapacağın iki ulaşım geçişin nakit iade! Kampanya Geçerlilik Tarihi: 30.11.2023-31.12.2023",kullanim: "Kullanıcının hafta içi toplamda 500 TL ve üzeri ulaşım dışı ödemesini takip eden hafta sonu aynı İstanbulkart’ı ile yapacağı 2 ulaşım geçişine denk gelen tutar nakit iade olacaktır.• Hafta sonu tek gün içinde yada ayrı günlerde de geçiş yapıldığında kampanyadan faydalanılabilir.Aynı hafta içinde yapılan 500 TL’lik ödemenin tamamının tek bir İstanbulkart ile yapılması gerekmektedir.• Ulaşım dışı ödemelerde koşulları sağlayan başarılı ödemelerden sonra ilgili ödemenin iptal işlemi gelmiş ise toplam tutara dahil edilmez. Kullanıcının toplam tutarına iptal-iade dışında kalan başarılı işlemler dahil edilecektir. • Kampanya dönemi boyunca kullanıcının hafta içi koşulları tamamlaması halinde her hafta sonu ulaşımda nakit iadesini alabilecektir.• Bir kullanıcı hafta sonunda tek bir kartı ile ödüllenebilir. Kullanıcı yalnızca ulaşım dışında ödeme koşulunu gerçekleştirdiği İstanbulkart ile ulaşım geçişini yapmalıdır.• Mesafe bazlı ücretlendirmelerde alınan iadeler yüklenecek ödül tutarından düşülecektir.Kazanılan ödülün nakit karşılığı talep edilemez.• Sosyal kartlar kampanyaya dahil değildir.• Kampanyadan faydalanabilmek için kampanyaya katılmadan önce açık rıza tercihlerinin açık olması ve en az bir ticari elektronik ileti izninin verilmiş olması gereklidir.• Açık rıza ve ticari elektronik ileti izinleri İstanbulkart Mobil’den ya da https://bireysel.istanbulkart.istanbul adresinde profil sayfasından düzenlenebilir.• Sistemsel gecikmelerden kaynaklı ödül TL yüklemelerinde oluşabilecek aksaklıklarda BELBİM AŞ müşteri memnuniyeti kapsamında TL ödül yüklemesini en kısa sürede gerçekleştirecektir.• Ödüllendirme bilgisi İstanbulkart Mobil kullanıcılarına push bildirimi ya da SMS olarak yapılacaktır.• Belbim AŞ kampanyayı durdurma ve değişiklik yapma hakkını saklı tutar.")
        
        
        let f9 = Basliklar(id: 9, resim: "kitapci", description: "İstanbulkart’ınla İstanbul Kitapçılarında yapacağın tüm alışverişlerinin %20’si nakit iade! Kampanya Geçerlilik Tarihi: 10.01.2024-10.02.2024",kullanim: "• İstanbul Kitapçısı’ndan İstanbulkart ile yapılan tüm alışverişlerin %20’si nakit iade edilecektir.• İstanbul Kitapçısına ait 14 şubeden İstanbulkart ile alışveriş yapılabilir. Mağaza bilgilerine https://www.istanbulkitapcisi.com/magazalarimiz linkinden ulaşabilirsin.• Kampanyadan faydalanabilmek için kampanyaya katılmadan önce İstanbulkart’ın kişiselleştirilmiş olması, açık rıza tercihlerinin açık olması ve en az bir ticari elektronik ileti izninin verilmiş olması gereklidir.• Açık rıza ve ticari elektronik ileti izinleri İstanbulkart Mobil’den ya da https://bireysel.istanbulkart.istanbul adresindeki profil sayfasından düzenlenebilir.• Kişiselleştirme işlemini yapmak, açık rıza ve ticari elektronik ileti izinlerini en kolay şekilde düzenlemek için bit.ly/istanbulkart_mobil adresinden İstanbulkart Mobil’i indirebilirsiniz.• Kampanya süresince kullanıcı birden fazla kez ödül alabilecek olup, toplamda en fazla 150 TL ödüllenebilir.• Kampanyaya tüm İstanbulkart kullanıcıları katılım sağlayabilecektir.• Yapılan işlemin gün içinde iptal edilmesi durumunda kullanıcı bu işleminden ödül alamayacaktır.• Kazanılan ödül, başarılı işlemin ertesi günü alışverişin yapıldığı İstanbukart’a talimat olarak yatırılacaktır.• Talimat olarak yüklenen ödül TL, İstanbulkart Mobil üzerinden NFC yoluyla, herhangi bir yükleme noktasına, otobüs duraklarında yer alan talimat yükleme noktalarına, otobüslerdeki geçiş cihazlarına İstanbulkart dokundurularak tanımlanabilir.• Kazanılan ödülün nakit karşılığı talep edilemez.• Ödüllendirme bilgisi İstanbulkart Mobil kullanıcılarına push bildirimi ya da SMS olarak yapılacaktır.• Sistemsel gecikmelerden kaynaklı ödül TL yüklemelerinde oluşabilecek aksaklıklarda BELBİM AŞ müşteri memnuniyeti kapsamında TL ödül yüklemesini en kısa sürede gerçekleştirecektir.• BELBİM AŞ kampanyayı durdurma ve değişiklik yapma hakkını saklı tutar.")
        
        basliklarListesi.append(f1)
        basliklarListesi.append(f2)
        basliklarListesi.append(f3)
        basliklarListesi.append(f4)
        basliklarListesi.append(f5)
        basliklarListesi.append(f6)
        basliklarListesi.append(f7)
        basliklarListesi.append(f8)
        basliklarListesi.append(f9)
        
        let tasarim = UICollectionViewFlowLayout()
        tasarim.sectionInset = UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)
        tasarim.minimumInteritemSpacing = 10
        tasarim.minimumLineSpacing = 10
        
        let ekranGenislik = UIScreen.main.bounds.width
        let itemGenislik = (ekranGenislik - 30) / 2
        tasarim.itemSize = CGSize(width: itemGenislik, height: itemGenislik*1.6)
        basliklarCollectionView.collectionViewLayout = tasarim
        
        super.viewDidLoad()
        self.navigationItem.title = "İstanbulKart"
        let appearance = UINavigationBarAppearance()
        appearance.backgroundColor = UIColor.systemBlue
        appearance.titleTextAttributes = [.foregroundColor:UIColor.white]
        
        navigationController?.navigationBar.standardAppearance = appearance
        navigationController?.navigationBar.compactAppearance = appearance
        navigationController?.navigationBar.scrollEdgeAppearance = appearance
        
    }
    


}

extension ViewController: UICollectionViewDelegate,UICollectionViewDataSource {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return basliklarListesi.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let baslik = basliklarListesi[indexPath.row]
        
        let hucre = collectionView.dequeueReusableCell(withReuseIdentifier: "basliklarHucre", for: indexPath) as! BasliklarHucre
        hucre.imageViewBaslik.image = UIImage(named: baslik.resim!)
        hucre.layer.borderColor = UIColor.lightGray.cgColor
        hucre.layer.borderWidth = 0.3
        hucre.layer.cornerRadius = 10.0
        
        return hucre
    }
    
    
}

